name: AT Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: npm ci
    - name: Start Node.js server
      run: npm start &
    - name: Wait for server to start
      run: sleep 5
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Test ganar
      run: npm run testGanar
    - name: Test perder
      run: npm run testPerder
    - name: Test vidas
      run: npm run testVidas
    - name: Test login
      run: npm run testLogin
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
