name: CI test

on: [push, pull_request]

jobs:

  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v3
    - run: cd /home/runner/work/juego-ahorcado/juego-ahorcado/backend
    - uses: gogaille/setup-monorepo-node-app@v1.1
      with:
        node-version: 14
        working-directory: ./backend
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
