name: CI test

on:
  push:
    branches: [ "prueba" ]
  pull_request:
    branches: [ "prueba" ]

jobs:

  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
    #- run: npm run test-cucumber
